### ISSUE TITLE
Audio Only Option for Live Podcasts on Web Player

### ISSUE THREAD

**Issue by eroc1990** [podverse/podverse-web#1088] opened 2023-02-14 21:09 UTC
Currently, clicking the Live button to launch a live podcast opens a video player if there's a video feed associated with the podcast. It would be nice if there was an option to stream _just_ the audio track for those of us who don't want/need video.

**Comment by mitchdowney** [comment] 2023-02-15 00:43
@eroc1990 good idea. I actually [just added this to the mobile app](https://podcastindex.social/@mitch/109861625279439625) v4.12.1 last night.

There may be limitations however. For example, if a livestream uses HLS (which they generally should, as they have wide adoption and robust feature support), then it will give us multiple options for streaming resolutions, ex. 1080p, 720p, 480p, etc. Sometimes HLS livestreams include a 0p option, which is the audio only version.

If an HLS stream *doesn't* provide a 0p option, then loading the video as an audio stream I don't think will make much sense, because it will still be the same large video file loading, instead of an audio only version.

So, I'm going to close this issue as a duplicate of #1085. Maybe we add audio only support for livestreams that don't properly support it some day, but at the moment I'm thinking we should avoid that and insist that podcasters provide a proper audio only stream with their HLS broadcast.

**Closed** 2023-02-15 00:43 UTC
Labels: duplicate, enhancement

**Comment by eroc1990** [comment] 2023-02-15 00:45
Sounds good! Thanks for taking the time to replyn
